name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: |
            npm install
            cp wrangler-example.toml wrangler.toml
            sed -i wrangler.toml -e 's/example\.com/${{ secrets.DOMAIN }}/g' -e 's/xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx/${{ secrets.DATABASE_ID }}/g'
          command: deploy
